name: Run Playwright Tests (Chrome)

on:
  push:
    branches:
      - main  # Runs on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting 'main'

jobs:
  tests:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the code in your repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install Python dependencies

      - name: Install Playwright and Chrome
        run: |
          python -m playwright install chromium  # Install only Chrome (Chromium)

      - name: Run Playwright tests (Chrome)
        run: |
          python -m pytest --browser=chromium  # Run the tests with Chrome browser
